# Generated by Django 6.0.7 on 2026-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='more_about_me',
            field=models.TextField(blank=True, null=True, verbose_name='بیشتر درباره کاربر'),
        ),
    ]
