# Generated by Django 6.0.7 on 2026-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پروژه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('url', models.URLField(max_length=300, verbose_name='لینک پروژه')),
                ('github_url', models.URLField(max_length=300, verbose_name='کد منبع در گیت هاب')),
                ('img', models.ImageField(upload_to='images/projects', verbose_name='تصویر')),
                ('skill', models.ManyToManyField(to='home.skill', verbose_name='ابزار استفاده شده')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
