# Generated by Django 6.0.7 on 2026-08-19 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLineRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع یادگیری')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیح کوتاه')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.projects', verbose_name='پروژه')),
                ('skill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.skill', verbose_name='مهارت')),
            ],
            options={
                'verbose_name': 'مسیر یادگیری',
                'verbose_name_plural': 'مسیرهای یادگیری',
            },
        ),
    ]
