# Generated by Django 6.0.7 on 2026-08-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=200, unique=True, verbose_name='عنوان در url'),
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام کاربر')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('answer', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='new', max_length=50, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
                ('admin_reply', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmessage_replied_by_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام ارتباط با ما',
                'verbose_name_plural': 'پیام های ارتباط با ما',
                'ordering': ['-created_at'],
            },
        ),
    ]
