# Generated by Django 6.0.7 on 2026-09-14 08:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='متن'),
        ),
    ]
